server {
    listen 80 default_server;
    server_name  _ *.vm docker;

    root  "/app/ci4/public";
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    include /opt/docker/etc/nginx/vhost.common.d/*.conf;

    error_page 404 /index.php;

    # deny access to hidden files such as .htaccess
    location ~ /\. {
        deny all;
    }
}